### ISSUE TITLE
Upon app launch, "Word or phrase" input box should be selected.

### ISSUE THREAD

**Issue by bryanpaget** [johnfactotum/quick-lookup#11]
## Description of Issue

When you launch the app, the cursor is in the language selection box which is not where I'd want to type the word I am interested in. Maybe this is by design but I find it to be counter to what I'd expect.

## As it is now:

![image](https://user-images.githubusercontent.com/8212170/97827805-3e9ff880-1cbd-11eb-9562-52b85ba5f15c.png)

## As I think it should be

![image](https://user-images.githubusercontent.com/8212170/97827915-7eff7680-1cbd-11eb-8a3f-6fb84119e037.png)

**Comment by johnfactotum** [comment]
This is indeed by design—or at least, the focus was explicitly set to the language selection box in the code. I can't really remember, though, why I coded it that way. And I suppose it does make more sense to focus on the query entry instead.

**Comment by gordebak** [comment]
I know this is an old post, but I'm a new user and the latest flatpak version still has the same issue.

**Comment by johnfactotum** [comment]
The fix was never released so the Flatpak version still has this issue. The app has since been ported to GTK 4 and released as 2.0.0 last year, which was not released for Flatpak because webkit2gtk-5.0 was not in the stable runtime yet. I _think_ it's in the 42 runtime now so I guess we can update the Flatpak to 2.0.0 now.
